using MAP2ADAMOINT.Models.Adamo;
using MAP2ADAMOINT.Models.MapTool;

namespace MAP2ADAMOINT.Services
{
    public class DataMapperService
    {
        private readonly ILogger<DataMapperService> _logger;

        public DataMapperService(ILogger<DataMapperService> logger)
        {
            _logger = logger;
        }

        /// <summary>
        /// Maps a MAP Tool Molecule to ADAMO MapInitial
        /// All fields from ADAMO MAP_INITIAL table (see docs/adamo-DATABASE_STRUCTURE.md)
        /// </summary>
        public MapInitial MapMoleculeToMapInitial(Molecule molecule, Map1_1MoleculeEvaluation? evaluation = null)
        {
            _logger.LogInformation("Mapping Molecule {GrNumber} to MapInitial", molecule.GrNumber);

            return new MapInitial
            {
                // ===== PRIMARY IDENTIFIERS =====
                // MapInitialId - Auto-generated by Oracle sequence (seq_map_initial_id)
                GrNumber = molecule.GrNumber ?? "",                    // REQUIRED: Unique molecule identifier
                RegNumber = molecule.RegNumber,                         // Auto-extracted from GR_NUMBER by Oracle trigger
                // Batch - Auto-extracted from GR_NUMBER by Oracle trigger (trailing digits)
                
                // ===== EVALUATION METADATA =====
                EvaluationDate = evaluation?.CreatedAt?.Date, // Date of evaluation from CreatedAt
                Chemist = molecule.ChemistName,                         // Chemist who performed evaluation
                // Assessor = evaluation?.Assessor,                     // TODO: Not available in MAP Tool Molecule - would need to track separately
                EvaluationSite = null,                                  // TODO: Map from evaluation.EvaluationSiteId (requires lookup table)
                
                // ===== DILUTION & PREPARATION =====
                Dilution = "10% in DPG",                                // TODO: Map from evaluation.GrDilutionSolventId (requires DilutionSolvent lookup)
                
                // ===== ODOR DESCRIPTIONS (Time-based) =====
                Odor0H = evaluation?.Odor0h,                            // Odor at 0 hours (initial)
                Odor4H = evaluation?.Odor4h,                            // Odor after 4 hours
                Odor24H = evaluation?.Odor24h,                          // Odor after 24 hours
                
                // ===== COMMENTS & NOTES =====
                Comments = $"Synced from MAP Tool | Status: {molecule.Status} | Project: {molecule.ProjectName ?? "N/A"}",
                
                // ===== AUDIT TRAIL =====
                CreationDate = DateTime.Now,                            // Auto-set by sync process
                CreatedBy = molecule.CreatedBy ?? "SYNC",               // User who created in MAP Tool or "SYNC"
                LastModifiedDate = DateTime.Now,                        // Auto-updated
                LastModifiedBy = molecule.UpdatedBy ?? "SYNC"           // Last user who modified
                
                // ===== FIELDS NOT MAPPED (Not available in MAP Tool) =====
                // Assessor - Would require separate tracking in Map1_1Evaluation
            };
        }

        /// <summary>
        /// Maps ADAMO MapSession + MapResult to MAP Tool Assessment
        /// All fields from MAP Tool Assessment table (see docs/maptool-DATABASE-DOCUMENTATION.md)
        /// </summary>
        public Assessment MapResultToAssessment(MapResult result, MapSession session)
        {
            _logger.LogInformation("Mapping MapSession {SessionId} to Assessment", session.SessionId);

            return new Assessment
            {
                // ===== PRIMARY IDENTIFIER =====
                // Id - Auto-generated by PostgreSQL

                // ===== SESSION METADATA =====
                SessionName = $"ADAMO-{session.SessionId}",            // Formatted session identifier
                DateTime = session.EvaluationDate ?? DateTime.Now,     // Date and time of assessment
                Stage = session.Stage ?? "Unknown",                     // MAP 0/1/2/3, ISC, FIB, FIM, CARDEX, RPMC
                
                // ===== GEOGRAPHIC & MARKET SEGMENTATION =====
                Region = session.Region ?? "",                          // Geographic region
                Segment = session.Segment ?? "",                        // CP (Consumer Preference) or FF (Fine Fragrance)
                
                // ===== STATUS =====
                Status = 1,                                             // TODO: Map ADAMO status codes to MAP Tool status codes
                IsClosed = false,                                       // Default to open - could check if session.ShowInTaskList == 'N'
                
                // ===== AUDIT TRAIL =====
                CreatedAt = DateTime.Now,                               // Auto-set by sync process
                CreatedBy = session.CreatedBy ?? result.CreatedBy ?? "SYNC",
                UpdatedAt = DateTime.Now,
                UpdatedBy = session.LastModifiedBy ?? result.LastModifiedBy ?? "SYNC",
                
                // ===== SOFT DELETE FLAGS =====
                IsArchived = false,                                     // Not archived by default
                IsManuallyArchived = false                              // Not manually archived
                
                // ===== FIELDS NOT DIRECTLY MAPPED =====
                // Status codes need verification - ADAMO may use different codes than MAP Tool
                // Participants from session could be stored separately in Map1_1Evaluation
                // SubStage and Category from ADAMO session not currently mapped
            };
        }

        /// <summary>
        /// Maps MAP Tool Map1_1MoleculeEvaluation to ADAMO MapResult
        /// All fields from ADAMO MAP_RESULT table (see docs/adamo-DATABASE_STRUCTURE.md)
        /// </summary>
        public MapResult MapMoleculeEvaluationToResult(Map1_1MoleculeEvaluation molEval, Map1_1Evaluation evaluation, long sessionId)
        {
            _logger.LogInformation("Mapping Map1_1MoleculeEvaluation {Id} to MapResult", molEval.Id);

            return new MapResult
            {
                // ===== PRIMARY IDENTIFIER =====
                // ResultId - Auto-generated by Oracle sequence (seq_map_result_id)
                
                // ===== SESSION LINKAGE =====
                SessionId = sessionId,                                  // REQUIRED: Foreign key to MAP_SESSION
                
                // ===== MOLECULE IDENTIFIERS =====
                GrNumber = molEval.Molecule?.GrNumber ?? "",           // REQUIRED: Molecule identifier
                RegNumber = molEval.Molecule?.RegNumber,               // Auto-extracted from GR_NUMBER by Oracle trigger
                // Batch - Auto-extracted from GR_NUMBER by Oracle trigger
                
                // ===== EVALUATION DATA =====
                Odor = molEval.Odor0h ?? molEval.Odor4h ?? molEval.Odor24h,  // Odor description (prioritize 0h)
                BenchmarkComments = molEval.Benchmark,                  // Comments comparing to benchmarks
                Result = molEval.ResultCP ?? molEval.ResultFF,          // Numeric result/score (1-5 scale typically)
                
                // ===== PREPARATION & SPONSORSHIP =====
                Dilution = "10%",                                       // TODO: Map from molEval.GrDilutionSolventId (requires DilutionSolvent lookup)
                Sponsor = evaluation.Participants,                      // Sponsor/participants information
                
                // ===== AUDIT TRAIL =====
                CreationDate = DateTime.Now,                            // Auto-set by sync process
                CreatedBy = "SYNC",                                     // Map1_1MoleculeEvaluation doesn't have CreatedBy field
                LastModifiedDate = DateTime.Now,                        // Auto-updated
                LastModifiedBy = "SYNC"                                 // Map1_1MoleculeEvaluation doesn't have UpdatedBy field
                
                // ===== FIELDS NOT DIRECTLY MAPPED =====
                // Dilution should be mapped from DilutionSolvent lookup table
                // Multiple odor descriptions available (0h, 4h, 24h) - currently using priority logic
                // ResultCP and ResultFF both available - using first non-null value
            };
        }

        /// <summary>
        /// Maps ADAMO OdorCharacterization to MAP Tool OdorFamily scores
        /// Note: This is a simplified mapping - full implementation would require
        /// creating OdorDetail records for each descriptor
        /// </summary>
        public Dictionary<string, int> ExtractOdorFamilyScores(OdorCharacterization odorChar)
        {
            _logger.LogInformation("Extracting odor family scores from {GrNumber}", odorChar.GrNumber);

            var scores = new Dictionary<string, int>();

            if (odorChar.AmbergrisFamily.HasValue)
                scores["AMBERGRIS_FAMILY"] = odorChar.AmbergrisFamily.Value;
            
            if (odorChar.AromaticHerbalFamily.HasValue)
                scores["AROMATIC_HERBAL_FAMILY"] = odorChar.AromaticHerbalFamily.Value;
            
            if (odorChar.CitrusFamily.HasValue)
                scores["CITRUS_FAMILY"] = odorChar.CitrusFamily.Value;
            
            if (odorChar.FloralFamily.HasValue)
                scores["FLORAL_FAMILY"] = odorChar.FloralFamily.Value;
            
            if (odorChar.FruityFamily.HasValue)
                scores["FRUITY_FAMILY"] = odorChar.FruityFamily.Value;
            
            if (odorChar.GreenFamily.HasValue)
                scores["GREEN_FAMILY"] = odorChar.GreenFamily.Value;
            
            if (odorChar.MarineFamily.HasValue)
                scores["MARINE_FAMILY"] = odorChar.MarineFamily.Value;
            
            if (odorChar.MuskyAnimalicFamily.HasValue)
                scores["MUSKY_ANIMALIC_FAMILY"] = odorChar.MuskyAnimalicFamily.Value;
            
            if (odorChar.OffOdorsFamily.HasValue)
                scores["OFF_ODORS_FAMILY"] = odorChar.OffOdorsFamily.Value;
            
            if (odorChar.SpicyFamily.HasValue)
                scores["SPICY_FAMILY"] = odorChar.SpicyFamily.Value;
            
            if (odorChar.SweetGourmandFamily.HasValue)
                scores["SWEET_GOURMAND_FAMILY"] = odorChar.SweetGourmandFamily.Value;
            
            if (odorChar.WoodyFamily.HasValue)
                scores["WOODY_FAMILY"] = odorChar.WoodyFamily.Value;

            return scores;
        }

        /// <summary>
        /// Maps ADAMO MapInitial back to MAP Tool Molecule
        /// All fields from MAP Tool Molecule table (see docs/maptool-DATABASE-DOCUMENTATION.md)
        /// </summary>
        public Molecule MapInitialToMolecule(MapInitial initial)
        {
            _logger.LogInformation("Mapping MapInitial {GrNumber} to Molecule", initial.GrNumber);

            return new Molecule
            {
                // ===== PRIMARY IDENTIFIER =====
                // Id - Auto-generated by PostgreSQL
                
                // ===== MOLECULE IDENTIFIERS =====
                GrNumber = initial.GrNumber,                            // Unique molecule identifier (e.g., "GR-88-0681-1")
                RegNumber = initial.RegNumber,                          // Registration number (base without batch)
                
                // ===== CHEMICAL INFORMATION =====
                ChemistName = initial.Chemist,                          // Name of chemist
                // ChemicalName = null,                                 // TODO: Not available in ADAMO MapInitial
                // MolecularFormula = null,                             // TODO: Not available in ADAMO MapInitial
                // Structure = null,                                    // TODO: Chemical structure - not in ADAMO MapInitial
                
                // ===== PROJECT & ASSESSMENT STATUS =====
                // ProjectName = null,                                  // TODO: Not available in ADAMO MapInitial
                Status = MoleculeStatus.Map1,                           // Default to Map1 status (evaluated and approved)
                Assessed = true,                                        // True since it exists in ADAMO (was assessed)
                
                // ===== QUANTITY =====
                Quantity = 0,                                           // TODO: Quantity not tracked in ADAMO - set to 0 as default
                
                // ===== AUDIT TRAIL =====
                CreatedAt = DateTime.Now,                               // Auto-set by sync process
                CreatedBy = initial.CreatedBy ?? "SYNC",               // User who created in ADAMO or "SYNC"
                UpdatedAt = DateTime.Now,                               // Auto-updated
                UpdatedBy = initial.LastModifiedBy ?? "SYNC",          // Last user who modified
                
                // ===== SOFT DELETE FLAGS =====
                IsArchived = false,                                     // Not archived by default
                IsManuallyArchived = false                              // Not manually archived
                
                // ===== FIELDS NOT AVAILABLE IN ADAMO =====
                // Structure - Chemical structure data not in ADAMO MAP_INITIAL
                // ChemicalName - IUPAC/common name not in ADAMO
                // MolecularFormula - Not in ADAMO
                // ProjectName - Project association not in ADAMO
                // Quantity - Inventory quantity not tracked in ADAMO
            };
        }
        
        /// <summary>
        /// Maps ADAMO MapSession to MAP Tool Map1_1Evaluation
        /// Creates evaluation record with session metadata
        /// </summary>
        public Map1_1Evaluation MapSessionToEvaluation(MapSession session, int assessmentId, int evaluationSiteId)
        {
            _logger.LogInformation("Mapping MapSession {SessionId} to Map1_1Evaluation", session.SessionId);

            return new Map1_1Evaluation
            {
                // ===== PRIMARY IDENTIFIER =====
                // Id - Auto-generated by PostgreSQL
                
                // ===== LINKAGE =====
                AssessmentId = assessmentId,                            // Foreign key to Assessment
                
                // ===== SESSION METADATA =====
                Participants = session.Participants,                    // List of session participants
                EvaluationDate = session.EvaluationDate,               // Date of evaluation
                EvaluationSiteId = evaluationSiteId,                   // Foreign key to EvaluationSite
                
                // ===== AUDIT TRAIL =====
                CreatedAt = DateTime.Now,
                CreatedBy = session.CreatedBy ?? "SYNC",
                UpdatedAt = DateTime.Now,
                UpdatedBy = session.LastModifiedBy ?? "SYNC"
                
                // ===== FIELDS NOT DIRECTLY MAPPED =====
                // EvaluationSiteId requires mapping from ADAMO site code to MAP Tool site ID
                // MoleculeEvaluations collection would be populated separately
            };
        }
        
        /// <summary>
        /// Maps ADAMO MapResult to MAP Tool Map1_1MoleculeEvaluation
        /// Creates molecule evaluation record with result data
        /// </summary>
        public Map1_1MoleculeEvaluation MapResultToMoleculeEvaluation(MapResult result, int evaluationId, int moleculeId, int sortOrder)
        {
            _logger.LogInformation("Mapping MapResult {ResultId} to Map1_1MoleculeEvaluation", result.ResultId);

            return new Map1_1MoleculeEvaluation
            {
                // ===== PRIMARY IDENTIFIER =====
                // Id - Auto-generated by PostgreSQL
                
                // ===== LINKAGE =====
                Map1_1EvaluationId = evaluationId,                     // Foreign key to Map1_1Evaluation
                MoleculeId = moleculeId,                               // Foreign key to Molecule
                SortOrder = sortOrder,                                 // Display order in evaluation
                
                // ===== DILUTION & PREPARATION =====
                // GrDilutionSolventId = null,                         // TODO: Parse from result.Dilution string
                // BenchmarkDilutionSolventId = null,                  // TODO: Not available in ADAMO
                
                // ===== ODOR DESCRIPTIONS =====
                Odor0h = result.Odor,                                  // Using ADAMO Odor as 0h description
                // Odor4h = null,                                      // TODO: ADAMO stores only single odor string
                // Odor24h = null,                                     // TODO: ADAMO stores only single odor string
                
                // ===== BENCHMARK & COMMENTS =====
                Benchmark = result.BenchmarkComments,                  // Benchmark comparison notes
                Comment = result.Sponsor != null ? $"Sponsor: {result.Sponsor}" : null,
                
                // ===== RESULTS & NEXT STEPS =====
                ResultCP = result.Result,                              // Using result as CP score
                ResultFF = result.Result,                              // Using same result for FF score
                // FFNextSteps = null,                                 // TODO: Not available in ADAMO
                // CPNextSteps = null,                                 // TODO: Not available in ADAMO
                
                // ===== AUDIT TRAIL =====
                CreatedAt = DateTime.Now,
                UpdatedAt = DateTime.Now
                
                // ===== FIELDS NOT AVAILABLE IN ADAMO =====
                // GrDilutionSolventId - ADAMO stores dilution as string, not FK
                // BenchmarkDilutionSolventId - Not tracked in ADAMO
                // Odor4h, Odor24h - ADAMO MAP_RESULT has single odor field
                // FFNextSteps, CPNextSteps - Not in ADAMO MAP_RESULT
                // Need to determine if result is CP or FF based on session segment
            };
        }
    }
}

